### PR TITLE
Split "Optional tasks" chapter

### PR DESCRIPTION
**Pull request by jawira**
Could you please double check that everything is ok please? I'm not a docbook expert :)

### CODE REVIEW

**Comment by jawira** [comment]
See issue #33

**Review by siad007 — CHANGES_REQUESTED** [review]
Wow - a lot of files!
After split there are two referencies left ~~and as much includes as files generated are missing~~ 😄 
See https://github.com/phingofficial/guide/search?q=optionaltasks.xml , where some includes are pointing to `source/appendixes/optionaltasks.xml`. ~~They have to be exchanged by every file referenced I guess or we should think about something like a register page, which includes then all single documentation files. WDYT? Without we are not able to navigate to the single doc pages.~~

**Comment by mrook** [comment]
Wow @jawira, this is great work.

**Comment by jawira** [comment]
Ok, sorry about the delay but I totally forgot about this PR.

There are two files referencing `optionaltasks.xml` https://github.com/phingofficial/guide/search?q=optionaltasks.xml
1. The first one is `master.xml`, I didn't change anything in this file since it simply does an `include`
2. I updated `source/chapters/about.xml` with new instructions.

Please don't hesitate to tell me if I have to change something else :)

**Comment by mrook** [comment]
@jawira can you update the PR?

**Comment by jawira** [comment]
Hello, I updated PR with changes from #35 and #36 , please let me know if something else is missing.

**Pull request merged**
